//Campaign Actions
export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const CAMPAIGN_ADD_SUCCESS = 'CAMPAIGN_ADD_SUCCESS';
export const CAMPAIGN_ADD_FAILED = 'CAMPAIGN_ADD_FAILED';

//Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//Donation Actions
export const DONATE = 'DONATE';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const DONATE_FAILED = 'DONATE_FAILED';
export const DONATE_ERROR = 'DONATE_ERROR';

export const DONATION_WITHDRAWN = 'DONATION_WITHDRAWN';
export const DONATION_WITHDRAWN_SUCCESS = 'DONATION_WITHDRAWN_SUCCESS';
export const DONATION_WITHDRAWN_FAILED = 'DONATION_WITHDRAWN_FAILED';
export const DONATION_WITHDRAWN_ERROR = 'DONATION_WITHDRAWN_ERROR';

export const DONATION_CLAIMED = 'DONATION_CLAIMED';
export const DONATION_CLAIMED_SUCCESS = 'DONATION_CLAIMED_SUCCESS';
export const DONATION_CLAIMED_FAILED = 'DONATION_CLAIMED_FAILED';

//Alert Actions
export const ALERT = 'ALERT';
