//App state
export const APP_LOADED = 'APP_LOADED';
export const ENABLE_METAMASK = 'ENABLE_METAMASK';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';

//User actions
export const SET_USER_DETAILS = 'SET_USER_DETAILS';

//Authentication Actions
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGN_OUT = 'SIGN_OUT';

//Campaign Actions
export const ADD_CAMPAIGN = 'ADD_CAMPAIGN';
export const CAMPAIGN_ADD_SUCCESS = 'CAMPAIGN_ADD_SUCCESS';
export const CAMPAIGN_ADD_FAILED = 'CAMPAIGN_ADD_FAILED';

//Profile Actions
export const UPDATE_PROFILE = 'UPDATE_PROFILE';

//Donation Actions
export const DONATE = 'DONATE';
export const DONATE_SUCCESS = 'DONATE_SUCCESS';
export const DONATE_FAILED = 'DONATE_FAILED';
export const DONATE_ERROR = 'DONATE_ERROR';

export const DONATION_WITHDRAWN = 'DONATION_WITHDRAWN';
export const DONATION_WITHDRAWN_SUCCESS = 'DONATION_WITHDRAWN_SUCCESS';
export const DONATION_WITHDRAWN_FAILED = 'DONATION_WITHDRAWN_FAILED';
export const DONATION_WITHDRAWN_ERROR = 'DONATION_WITHDRAWN_ERROR';

export const DONATION_CLAIMED = 'DONATION_CLAIMED';
export const DONATION_CLAIMED_SUCCESS = 'DONATION_CLAIMED_SUCCESS';
export const DONATION_CLAIMED_FAILED = 'DONATION_CLAIMED_FAILED';

//Alert Actions
export const ALERT = 'ALERT';

//Transaction States Actions
export const ADD_TRANSACTION_STATE = 'ADD_TRANSACTION_STATE';
export const SET_TRANSACTION_STATE = 'SET_TRANSACTION_STATE';